name: CI workflows
on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1

            - name: Install dependencies
              run: bun install

            - name: Run TypeScript Compiler
              run: bun run build
