name: Docker build

on: [push]

jobs:
    docker:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                service:
                  - ws
                  - api
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GCR
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: ghcr.io/${{ github.repository }}/${{ matrix.service }}:latest
                  file: Dockerfile.${{ matrix.service }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
    deploy:
        name: Deploy on droplet
        needs: [docker]
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using ssh key
              uses: appleboy/ssh-action@master
              with:
                  host: 192.241.148.27
                  username: root
                  password: ${{ secrets.VPS_PASSWORD }}
                  port: 22
                  script: |
                      cd 312p2
                      bun p pull
                      bun p up -d --force-recreate ws api caddy mongo